name: "check for Dependabot merge conflicts"
on:
  push:
    branches: main
  pull_request_target:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if PR has conflict
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "PR: needs recreation"
          removeOnDirtyLabel: "PR: ready to ship"
          repoToken: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          commentOnDirty: "@Dependabot recreate"
